### ISSUE TITLE
error

### ISSUE THREAD

**Issue by almeidx** [Almeeida/Simplicity#220]
**Describe the bug**
error

**To Reproduce**
1. Exist

**Expected behavior**
not to error

**Screenshots**
![image](https://user-images.githubusercontent.com/42935195/83758479-0f338400-a66a-11ea-8f5b-cfe37b85cc0a.png)

**Comment by Tsugami** [comment]
fix https://github.com/Simplicity/Simplicity/commit/17c0fef936f44e0c6b3bbe4b38c46aac3d8cd44b
